//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myblog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public post()
        {
            this.comments = new HashSet<comment>();
        }
    
        public int postID { get; set; }
        public string username { get; set; }
        public System.DateTime date { get; set; }
        public string body { get; set; }
        public string title { get; set; }
        public string imageURL { get; set; }
        public int likes { get; set; }
    
        public virtual author author { get; set; }
        public virtual ICollection<comment> comments { get; set; }
    }
}
